### ISSUE TITLE
No Upload Speed for Cloudflare

### ISSUE THREAD

**Issue by joezimjs** [bitfocus/companion-module-generic-speedtest#14]
Companion v3.3.1
When I run a Cloudflare speed test, the upload speed variable never gets filled.

![image](https://github.com/bitfocus/companion-module-generic-speedtest/assets/1313898/ac925390-f2a2-4e09-b159-4adc93058b9b)

**Comment by bryce-seifert** [comment]
I've finally found the root of the issue, it looks like the format of the server-timing response has changed, and this is not accounted for in the module, universal-speediest, we use which is causing it to not process the upload data.

I'm going to look at fixing this this weekend, whether by patching that module or transitioning to the official Cloudflare module

**Comment by joezimjs** [comment]
Awesome. I was just looking at it today and noticed you were using a dependency to run the tests that hasn't been updated in 2 years... If I had the time I'd be jumping on this fix myself.

**Comment by bryce-seifert** [comment]
I looked at fixing this weekend, but was having issues building the speedtest library after implanting the fix, probably due to its age.

I also tried the Cloudflare library, but it doesn’t seem to play nicely with Node. 

I can’t find an obvious better library, so I’m going to keep investigating the build issues

**Comment by ChrisSW58** [comment]
As a matter of interest, is Speedtest.net working correctly - just loops for me....

**Comment by joezimjs** [comment]
> As a matter of interest, is Speedtest.net working correctly - just loops for me....

Nope. Never seems to finish a speed test.

**Comment by ChrisSW58** [comment]
Hi Bryce - any update on this please?

**Comment by ChrisSW58** [comment]
I understand the 3.4.0 stable release is imminent… presumably a fix for this won’t make it, unfortunately?

**Comment by bryce-seifert** [comment]
@ChrisSW58 I'm going to try to my best to get it patched, it's just been a busy couple of weeks.,

If you're able, can you download this [test build](https://www.dropbox.com/scl/fi/34hav7q1g90yrro925122/companion-module-generic-speedtest.tgz?rlkey=59ixaxlsjic4538mcyax5lvoc&st=olom4zdp&dl=0) and run it in Companion using the Developer Modules patch in the main window, and let me know if that build works for you?

**Comment by joezimjs** [comment]
I tried it and it works for me! Thanks @bryce-seifert

**Comment by ChrisSW58** [comment]
That has sorted the issue Bryce - many thanks and very well done. Just FYI, the SpeedTest.net option still loops and never ends, but I assume you have not looked at that code. Many thanks once again.

**Comment by ChrisSW58** [comment]
Bryce - just updated to Companion beta 7240 with your module version 1.0.3. SpeedTest starts and then stops immediately. Was working fine in the test build.

**Comment by bryce-seifert** [comment]
@ChrisSW58 What OS are you on? Are there any errors in the module log? 

Also can you confirm cloudflare is still good in the build for you? It’s just Speedtest?

**Comment by ChrisSW58** [comment]
@bryce-seifert It's very weird - your test build is now timing out even if I go back beta builds. Am running on MacOS. Logs attached. 
[7240 1.0.3 module-log-30_08_2024-13_08_46.csv](https://github.com/user-attachments/files/16816772/7240.1.0.3.module-log-30_08_2024-13_08_46.csv)
[7240 with test build module on SpeedTest-log-30_08_2024-13_06_00.csv](https://github.com/user-attachments/files/16816773/7240.with.test.build.module.on.SpeedTest-log-30_08_2024-13_06_00.csv)

**Comment by bryce-seifert** [comment]
And this is only for Speedtest option? Cloudflare is still fine?

**Comment by ChrisSW58** [comment]
Here's the full log same for either service. 
<img width="951" alt="Screenshot 2024-08-30 at 1 18 52 pm" src="https://github.com/user-attachments/assets/2837b98a-de24-4b3f-afc2-dd31dc658a59">

**Comment by bryce-seifert** [comment]
Just to verify, in the latest beta, are you running the “Run Speedtest” action after starting the module? I changed it from running automatically in order to try and avoid the “call timed out” error

**Comment by ChrisSW58** [comment]
I'm clearing the log file and then starting the connection from there. I reverted to your test module and did the same and it now seems to be OK - maybe I cocked it up before! 
<img width="1317" alt="Screenshot 2024-08-30 at 1 26 47 pm" src="https://github.com/user-attachments/assets/b3d0c538-c974-447e-90ee-f740dae519e3">

**Comment by ChrisSW58** [comment]
Here is the log from the 7240 having started the module the same way, and also the variables from it
<img width="1013" alt="Screenshot 2024-08-30 at 1 30 58 pm" src="https://github.com/user-attachments/assets/e9616440-6420-4503-8402-ed82a7556368">
<img width="1433" alt="Screenshot 2024-08-30 at 1 31 21 pm" src="https://github.com/user-attachments/assets/dabccc18-2868-45db-9d27-3f8a55bfb77d">

**Comment by ChrisSW58** [comment]
Thanks for your prompt response by the way - much appreciated

**Comment by bryce-seifert** [comment]
In the latest beta (different from the test build), you will need to run the “Run Speedtest” action after starting the module. Perhaps I should change the “Stopped” variable to “Not Yet Run” or similar to indicate this behavior change

**Comment by bryce-seifert** [comment]
No worries, yes I agree that I need to update the help documentation now that it’s functional.

Just curious, are both Speedtest and cloudflare services working for you now?

**Comment by ChrisSW58** [comment]
No - Speediest looping as always on 5 sec timeout - here's the log
<img width="1320" alt="Screenshot 2024-08-30 at 1 49 23 pm" src="https://github.com/user-attachments/assets/26879516-ba2f-490f-8cec-7c2e51a3aa34">

**Comment by bryce-seifert** [comment]
Got it , thank you for the log on that that is a helpful error. I will try and diagnose that next

**Comment by bryce-seifert** [comment]
@ChrisSW58 I believe speedtest.net tests should be fixed in the latest Companion beta.

**Comment by patrichard** [comment]
Just updated to the latest beta and seems to be fine for me. Thanks for all of the hard work.

**Comment by ChrisSW58** [comment]
Yes! Both options working successfully. Many thanks for all your hard work
