### ISSUE TITLE
No download speed on Cloudflare

### ISSUE THREAD

**Issue by ChrisSW58** [bitfocus/companion-module-generic-speedtest#15]
All working fine on Cloudflare but now the upload speed variable is staying as empty. Happens on current stable Companion and on latest beta release, and on Mac Silicon and Windows 11 on different sites. Has something changed at Cloudflare? (We're UK based)
![Screenshot 2024-07-01 at 3 43 55 am](https://github.com/bitfocus/companion-module-generic-speedtest/assets/137667519/ea0696f8-03fa-46e6-aad9-1144b34cb685)

**Comment by ChrisSW58** [comment]
Issue still with us - I assume Cloudflare has changed its API in some way to either not return the value, or moved the value to another field. Is anyone maintaining this module?

**Comment by ChrisSW58** [comment]
Still no download speed from Cloudflare. Is there any way to escalate to Cloudflare to ask what has happened or if they have removed that data from the call? Moving to Speedtest.net is not an option as I have never been able to use that - it goes into a permanent loop timing out after 5 secs and then just keeps retrying. I then have to abort Companion and restart it before I can change the test back to Cloudflare. PS I'm UK based in case that affects anything.

**Comment by bryce-seifert** [comment]
It looks like based on your screenshot the issue is with upload speed, which is covered under 
https://github.com/bitfocus/companion-module-generic-speedtest/issues/14
